### ISSUE TITLE
ValueError: 'DOOMBOTSTEEMO' is not a valid GameMode

### ISSUE THREAD

**Issue by pfmoore** [meraki-analytics/cassiopeia#114]
Referencing a game mode can give an error. It looks like the "Doom bots of Doom" special mode includes a champion name in the mode.

```python
>>> from cassiopeia import riotapi
>>> riotapi.set_region('euw')
>>> riotapi.set_api_key(my_key)
>>> g = riotapi.get_match(3217348141) # Example of a doom bots game
>>> g.mode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Gustav\AppData\Local\Temp\VE-1\lib\site-packages\cassiopeia\type\core\match.py", line 77, in mode
    return cassiopeia.type.core.common.GameMode(self.data.matchMode) if self.data.matchMode else None
  File "C:\Users\Gustav\AppData\Local\Temp\VE-1\lib\enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Gustav\AppData\Local\Temp\VE-1\lib\enum.py", line 533, in __new__
    return cls._missing_(value)
  File "C:\Users\Gustav\AppData\Local\Temp\VE-1\lib\enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'DOOMBOTSTEEMO' is not a valid GameMode
```

**Comment by jjmaldonis** [comment]
Thanks! If you re-pull from github it should be fixed now.

**Comment by pfmoore** [comment]
Fast work! Thanks very much :-)
