### ISSUE TITLE
Items missing in dto raise exception instead of returning a default value

### ISSUE THREAD

**Issue by 10se1ucgo** [meraki-analytics/cassiopeia#132]
There are certain cases where it makes sense to return a default value instead of raising an exception when an item is missing from the dto.

e.g.:
```python
>>> item.stats.health
325
>>> item.stats.percent_health
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Program Files\Python36\lib\site-packages\cassiopeia\core\staticdata\item.py", line 161, in percent_health
    return self._dto["PercentHPPoolMod"]
KeyError: 'PercentHPPoolMod
```
Instead of raising KeyError, it would make more sense to return 0. 

Solutions:
1. Use `self._dto.get("attr", default)`
2. Implement default values in the dto `__init__`

**Comment by jjmaldonis** [comment]
Agreed, in many cases it does make sense to have default values. Right now we have implemented some defaults in the `datasources/riotapi` files, and more can and probably should be added as we find them.

There are also a few cases where having a default value makes less sense, and Rob and I were just talking about them yesterday.  For example, if you request the `Leagues` for a summoner, it returns a list of `LeagueEntry`s for all the 40ish summoners in that league. If a summoner is not in his/her promo series, the `MiniSeries` entry is not included in Riot's returned data. Does it make sense to have a default value in that case? Maybe, maybe not. We haven't come to a solid decision on that yet.

So there are certainly some cases (like the stats above) that present pretty clear-cut cases where we should implement default values, but other cases are not clear. For the former cases that are clear, I'm leaning towards using `dict.set_default("attr", default)` in the `datasources/riotapi` files.

**Comment by jjmaldonis** [comment]
A few more comments as we've been thinking about this.

1) We decided that things like a summoner's MiniSeries (which is returned by the Riot API if the summoner is in their promos, and is entirely absent if not) will be set to `None` if it doesn't exist. However, things like `Champion(id=12345)` and summoners with an incorrect name will throw an error when they are loaded.

2) The static data changes by patch, which makes implementing some of these fixes for static data a significant problem. We haven't thought about this a ton except to note that it is a problem.

**Comment by jjmaldonis** [comment]
Small update:

* `LeagueEntry.promos` returns `None` if the summoner isn't in their promos

* `MasteryPage.masteries` and `RunePage.runes` return empty dicts if the summoner doesn't have any masteries / runes in their page...
