### ISSUE TITLE
ModuleNotFoundError: No module named 'championgg'

### ISSUE THREAD

**Issue by fompei** [meraki-analytics/cassiopeia#141]
I installed cassiopeia using Anaconda environment but when trying to run champion.py example file but I'm encountering this error. Any idea how to fix it?

```
Traceback (most recent call last):
  File "testcass.py", line 35, in <module>
    get_champions()
  File "testcass.py", line 7, in get_champions
    annie = Champion(name="Annie", region="NA")
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/core/common.py", line 41, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/core/common.py", line 170, in __call__
    pipeline = configuration.settings.pipeline
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 116, in pipeline
    self.__pipeline = create_pipeline(verbose=False, service_configs=self.__pipeline_args)  
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 27, in create_pipeline  
    module = importlib.import_module(name=package)  
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/importlib/__init__.py", line 126, in import_module  
    return _bootstrap._gcd_import(name[level:], package, level)  
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import  
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked  
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed  
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import  
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked  
ModuleNotFoundError: No module named 'championgg'  
```

**Comment by jjmaldonis** [comment]
Hmm that is strange. Can you post the contents of the testcass.py file that is being run?

**Comment by fompei** [comment]
It is very similar to the 'champion.py' file that you put in the example folder. I just added two lines. 

```
import cassiopeia as cass
from cassiopeia import Champion


def get_champions():
    # annie = Champion(name="Annie", region="NA")
    annie = Champion(name="Annie", region="NA")
    print(annie.name)
    print(annie.title)
    for spell in annie.spells:
        print(spell.name, spell.keywords)

    print(annie.info.difficulty)
    print(annie.passive.name)
    print({item.name: count for item, count in annie.recommended_itemsets[0].item_sets[0].items.items()})
    print(annie.free_to_play)
    print(annie._Ghost__all_loaded)

    # ziggs = cass.get_champion(region="NA", "Ziggs")
    ziggs = cass.get_champion("Ziggs", region="NA")
    print(ziggs.name)
    print(ziggs.region)
    print({item.name: count for item, count in ziggs.recommended_itemsets[0].item_sets[0].items.items()})
    print(ziggs.free_to_play)
    for spell in ziggs.spells:
        for var in spell.variables:
            print(spell.name, var)
    print(ziggs._Ghost__all_loaded)

    quinn = cass.get_champion("Quinn", region="NA")
    print(quinn) 


if __name__ == "__main__":
    get_champions()
```

**Comment by jjmaldonis** [comment]
Shoot, thanks. This was a bug. I just fixed it here:  https://github.com/meraki-analytics/cassiopeia/commit/5ee1a12926f949a48273e6511f32f4eeeac3290d

You can do the same thing, or pull the latest version from github to get that change. I'll make a new release to pypi sometime soon.

**Comment by fompei** [comment]
Alright thanks. I'm not entirely sure if the program runs fine now but I'll ask again if any other issues arises :+1:
