### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by fompei** [meraki-analytics/cassiopeia#142]
This issue is tied with #141 to some degree. 
I've been trying to install cassiopeia on Anaconda environment but several issues arise. 
One of them being the championgg module which was fixed.  

My process was this:
1. `conda create --name league python=3.6`
2. `source activate league`
3. `pip install git+https://github.com/meraki-analytics/cassiopeia.git`
4. run `python testcass.py` (same as champion.py in examples folder)

At this point, I get this error

```
  File "testcass.py", line 1, in <module>
    import cassiopeia as cass
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/__init__.py", line 5, in <module>
    from .cassiopeia import get_realms, get_challenger_league, get_champion_masteries, get_champion, get_champion_mastery, get_champions, get_current_match, get_featured_matches, get_items, get_language_strings, get_locales, get_league_positions, get_leagues, get_maps, get_master_league, get_masteries, get_mastery_pages, get_match, get_match_history, get_patch, get_profile_icons, get_rune_pages, get_runes, get_status, get_summoner, get_summoner_spells, get_version, get_versions
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 7, in <module>
    from .datastores import common as _common_datastore
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/datastores/__init__.py", line 2, in <module>
    from .riotapi import RiotAPI
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/__init__.py", line 5, in <module>
    from .common import RiotAPIService, RiotAPIRateLimiter
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/common.py", line 11, in <module>
    from ..common import HTTPClient, HTTPError, Curl
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/datastores/common.py", line 8, in <module>
    from pycurl import Curl
ImportError: pycurl: libcurl link-time version (7.47.0) is older than compile-time version (7.55.1)
```
5. I used `conda install pycurl` to update pycurl. This solves the previous error.
6. Tried running `python testcass.py` again but this time I get this

```
Traceback (most recent call last):
  File "testcass.py", line 35, in <module>
    get_champions()
  File "testcass.py", line 7, in get_champions
    annie = Champion(name="Annie", region="NA")
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/core/common.py", line 41, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/core/common.py", line 170, in __call__
    pipeline = configuration.settings.pipeline
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 112, in pipeline
    self.__pipeline = create_pipeline(verbose=False, service_configs=self.__pipeline_args)
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 34, in create_pipeline
    pipeline = DataPipeline(services, transformers)
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/datapipelines/pipelines.py", line 283, in __init__
    self._type_graph = _build_type_graph(sources, sinks, transformers)
  File "/home/aaron/anaconda3/envs/league/lib/python3.6/site-packages/datapipelines/pipelines.py", line 71, in _build_type_graph
    current_transformer = graph.edge[from_type][to_type][_TRANSFORMER]
AttributeError: 'DiGraph' object has no attribute 'edge'
```
Is this an issue on my end or something else?

**Comment by jjmaldonis** [comment]
What happens if you use `conda install networkx` to update networkx? I don't know why anaconda wouldn't be using the latest versions.

The pycurl is a pain point we are trying to address too. I've never seen the `DiGraph` error though. You may just want to try updating all your conda packages.

**Comment by fompei** [comment]
Yup that fixed it. Thanks for the help

**Comment by jjmaldonis** [comment]
Eviently networkx made a major update and went from 1.x to 2.x. 2.x has some API breaking changes, which is what is causing this error.

I'm reopening this because it will be an issue for other people until we decide if we are going to make Cass backward compatible with networkx 1.x, require networkx 1.x, or update and require networkx 2.x.

**Comment by MatrixSenpai** [comment]
I can attest to this as well, downgrading to networks 1.11 (`pip install "networkx<2.0"`) solves this issue. As a hot fix, require this version in setup.py?

**Comment by jjmaldonis** [comment]
Thanks. This is in fact an issue with datapipelines rather than cass, and the correct fixes have been made to datapipelines to make it compatible with any version of networkx. However, we haven't made new releases of things yet. You can also pull the latest version of datapipelines if you'd like the fixes (and therefore be able to use the new version of netwokx). I'll try to make releases sometime this week, but it's going to be a busy one.

**Comment by jjmaldonis** [comment]
I just made the releases of the necessary packages. Everything should be on pypi within a few minutes.

**Comment by MatrixSenpai** [comment]
Well...
```
Traceback (most recent call last):
  File "__init__.py", line 13, in <module>
    main()
  File "__init__.py", line 9, in main
    senpai = cass.get_summoner(name="MatrixSenpai")
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 84, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/cassiopeia/core/common.py", line 41, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/cassiopeia/core/common.py", line 170, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 116, in pipeline
    self.__pipeline = create_pipeline(verbose=False, service_configs=self.__pipeline_args)
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 34, in create_pipeline
    pipeline = DataPipeline(services, transformers)
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/datapipelines/pipelines.py", line 283, in __init__
    self._type_graph = _build_type_graph(sources, sinks, transformers)
  File "/Users/matrixsenpai/.pyenv/versions/3.6.1/lib/python3.6/site-packages/datapipelines/pipelines.py", line 71, in _build_type_graph
    current_transformer = graph.edge[from_type][to_type][_TRANSFORMER]
AttributeError: 'DiGraph' object has no attribute 'edge'
```
Running:
```
$ pip show cassiopeia
Name: cassiopeia
Version: 3.0.14
...
```
```
$ pip show networkx
Name: networkx
Version: 2.0
...
```
Staying on 1.x runs fine

**Comment by jjmaldonis** [comment]
Maybe `datapipelines` isn't being updating with Cass. Cass's dependencies should enforce the correct version of `datapipelines`, but maybe something isn't working. Just update `datapipelines` via pip and you'll be good.

**Comment by MatrixSenpai** [comment]
Ah, thanks. That worked
