### ISSUE TITLE
[HELP]Can't use cassiopeia-championgg

### ISSUE THREAD

**Issue by Shnatta** [meraki-analytics/cassiopeia#152]
# Can't use championgg data for some reason?

## Error:
```
  File "champion_gg.py", line 46, in pro
    annie = Champion(name="Annie", id=1, region="NA")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/core/common.py", line 41, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/core/common.py", line 170, in __call__
    pipeline = configuration.settings.pipeline
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 120, in pipeline
    self.__pipeline = create_pipeline(verbose=False, service_configs=self.__pipeline_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 27, in create_pipeline
    module = importlib.import_module(name=package)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cassiopeia-plugins'
```

## Pipeline setup
```
_defaults = {
    "global": {
        "version_from_match": "patch",
        "default_region": None
    },
    "plugins": {},
    "pipeline": {
        "Cache": {},
        "UnloadedGhostStore": {},
        "DDragon": {},
        "RiotAPI": {
            "api_key": "HIDDEN"
        },
        "ChampionGG":{
            "package": "cassiopeia-plugins.championgg.championgg",
            "api-key": "HIDDEN"
        }
    },
    "logging": {
        "print_calls": True,
        "print_riot_api_key": False,
        "default": "WARNING",
        "core": "WARNING"
    }
}
```

## My whole code
```
import cassiopeia as cass
from cassiopeia import Champion
import time as t

def pro():
    annie = Champion(name="Annie", id=1, region="NA")
    print(annie.name)

    print(annie.championgg.win_rate)
    print(annie.championgg.play_rate)
    print(annie.championgg.play_rate_by_role)
    print(annie.championgg.ban_rate)
    print(annie.championgg.games_played)
    print(annie.championgg.damage_composition)
    print(annie.championgg.kills)
    print(annie.championgg.total_damage_taken)
    print(annie.championgg.wards_killed)
    print(annie.championgg.neutral_minions_killed_in_team_jungle)
    print(annie.championgg.assists)
    print(annie.championgg.performance_score)
    print(annie.championgg.neutral_minions_killed_in_enemy_jungle)
    print(annie.championgg.gold_earned)
    print(annie.championgg.deaths)
    print(annie.championgg.minions_killed)
    print(annie.championgg.total_healed)
    print(annie.championgg.championgg_metadata["elo"])
    print(annie.championgg.championgg_metadata["patch"])


if (__name__ == "__main__"):
    pro()
```

**Comment by jjmaldonis** [comment]
Rather than using

    "package": "cassiopeia-plugins.championgg.championgg",

use 

    "package": "cassiopeia_championgg",

I'll update this in the docs, I thought I fixed it.

Also, I just made a new release of cassiopeia-championgg to pypi to fix some bugs. Please update and make sure you have version 1.0.1. It might take a few minutes for the package to propagate through pypi, but usually less than 10 min.

**Comment by Shnatta** [comment]
> Updated cassiopeia-championgg to 1.0.1
## New error:
```
Traceback (most recent call last):
  File "champion_gg.py", line 68, in <module>
    pro()
  File "champion_gg.py", line 45, in pro
    annie = Champion(name="Xin Zhao", id=1, region="NA")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/core/common.py", line 41, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/core/common.py", line 170, in __call__
    pipeline = configuration.settings.pipeline
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 120, in pipeline
    self.__pipeline = create_pipeline(verbose=False, service_configs=self.__pipeline_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 29, in create_pipeline
    store = store_cls(**config)
TypeError: __init__() got an unexpected keyword argument 'api-key'
```
## pipeline setup
```
_defaults = {
    "global": {
        "version_from_match": "patch",
        "default_region": None
    },
    "plugins": {},
    "pipeline": {
        "Cache": {},
        "UnloadedGhostStore": {},
        "DDragon": {},
        "RiotAPI": {
            "api_key": "HIDDEN"
        },
        "ChampionGG":{
            "package": "cassiopeia_championgg",
            "api-key": "HIDDEN"
        }
    },
    "logging": {
        "print_calls": True,
        "print_riot_api_key": False,
        "default": "WARNING",
        "core": "WARNING"
    }
}
```

**Comment by jjmaldonis** [comment]
You have `api-key` rather than `api_key` in your config.

**Comment by Shnatta** [comment]
Oh i see, but it again gives me another error.
```
Traceback (most recent call last):
  File "champion_gg.py", line 50, in <module>
    pro()
  File "champion_gg.py", line 46, in pro
    print(annie.championgg.win_rate)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/merakicommons/cache.py", line 18, in wrapper
    values[self] = method(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia_championgg/__init__.py", line 19, in championgg
    return ChampionGGStats(id=self.id, patch=Patch.from_str(".".join(self.version.split(".")[:-1])), region=self.region)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cassiopeia/patches.py", line 32, in from_str
    raise ValueError("Unknown patch name {}".format(string))
ValueError: Unknown patch name 7.21
```

**Comment by jjmaldonis** [comment]
Ah, `championgg` requires you to have the latest patch in the json file. You just need to add it (we'll push it sometime soon, just haven't gotten to it). `cassiopeia/patches.json` is the filename you need to edit.

**Comment by Shnatta** [comment]
Ok i tried to add
```
  {
    "season": "Season 7",
    "name": "7.21",
    "start": 1507680000.0,
    "end": null
  }
```
but i think the start variable is somehow wrong?
