### ISSUE TITLE
Issue with match history

### ISSUE THREAD

**Issue by Satrium** [meraki-analytics/cassiopeia#159]
While using cassio i stumpled over the follwing error:

`Traceback (most recent call last):
  File "main.py", line 55, in <module>
    collect_matches()
  File "main.py", line 35, in collect_matches
    for match in matches:
  File "/home/anton/workspace/yordler/cassio-testing/env/lib/python3.5/site-packages/merakicommons/container.py", line 348, in __iter__
    yield next(self)
  File "/home/anton/workspace/yordler/cassio-testing/env/lib/python3.5/site-packages/merakicommons/container.py", line 358, in __next__
    value = next(self._generator)
  File "/home/anton/workspace/yordler/cassio-testing/env/lib/python3.5/site-packages/cassiopeia/transformers/match.py", line 109, in match_generator
    for matchrefdata in gen:
  File "/home/anton/workspace/yordler/cassio-testing/env/lib/python3.5/site-packages/cassiopeia/transformers/match.py", line 47, in match_dto_to_data_generator

    for matchrefdto in generator:
  File "/home/anton/workspace/yordler/cassio-testing/env/lib/python3.5/site-packages/cassiopeia/datastores/riotapi/match.py", line 227, in generate_matchlists
    for matchdto in data["matches"]:
TypeError: list indices must be integers or slices, not str`

This seems to only happen if the match history is empty and the api returns 404, i.e. the summoner hasn't played a game matching the provided filters.
To reproduce this error simply request the match history for custom games which doesn't return any matches because custom games are not public.

**Comment by jjmaldonis** [comment]
Thanks, I'll check it out. I'll take a look at your PR tomorrow too.
