### ISSUE TITLE
(object has no attribute) FrameData in Match timelines is incomplete

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#168]
Trying to retrieve the participant_frames from FrameData gives:
```
>>> m.timeline.frames[0].participant_frames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterli/Projects/cassiopeia/cassiopeia/core/match.py", line 590, in participant_frames
    return SearchableDictionary({k: ParticipantFrame.from_data(frame) for k, frame in self._data[FrameData].participant_frames.items()})
AttributeError: 'FrameData' object has no attribute 'participant_frames'
```

The data does get serialized and put into `_participant_frames` and the to_json does return the data. However the json returns multiple of the same value. Each frame should return a `participant_frames` array containing the 10 players but `_participant_frames` contains 10 copies of the array, resulting in a 10x blowup of the data

**Comment by tyuo9980** [comment]
@jjmaldonis the issue has not been fixed. 

```
>>> import cassiopeia
>>> cassiopeia.set_riot_api_key("RGAPI-ffff0aba-ba5a-8d96-8fc0-5003052014f3")
>>> cassiopeia.set_default_region("NA")
>>> cassiopeia.get_match(2650476106)
>>> m = cassiopeia.get_match(2650476106)
>>> m.timeline.frames[0].participant_frames
m.timeline.frames[0].participant_frames)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterli/Projects/cassiopeia/cassiopeia/core/match.py", line 574, in participant_frames
    return SearchableDictionary({k: ParticipantFrame.from_data(frame) for k, frame in self._data[FrameData].participant_frames.items()})
AttributeError: 'FrameData' object has no attribute 'participant_frames'
```

**Comment by jjmaldonis** [comment]
Should be fixed now. Also don't forget to regen your API key.
