### ISSUE TITLE
get_current_match.bannedChampions not exposed

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#191]
There is no property to access bannedChampions.

Also get_currnet_match.team.bans throws this err:

```
>>> c.blue_team.bans
Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Team' object has no attribute '_lazy__bans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/spectator.py", line 164, in bans
    return {pick: Champion(id=championId, region=self.__match.region, version=get_latest_version(region=self.__match.region, endpoint="champion")) for pick, championId in self._data[TeamData].bans.items()}
AttributeError: 'list' object has no attribute 'items'
```

**Comment by jjmaldonis** [comment]
The issue with `current_match.blue_team.bans` is now fixed. We decided that this data format is better than `current_match.bans` because it provides all the information more clearly and easily, so you'll have to use that method to access the bans.
