### ISSUE TITLE
runes static data description properties not working

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#198]
happens with short_description, long_description, and end of game descriptions

```
>>> r[0].short_description
Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/staticdata/rune.py", line 200, in short_description
    return self._data[RuneData].short_description
AttributeError: 'RuneData' object has no attribute 'short_description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/ghost.py", line 87, in __get__
    return self.fget(obj)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'RuneData' object has no attribute 'short_description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/merakicommons/ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 240, in __load__
    raise ValueError("object has already been loaded.")
ValueError: object has already been loaded.
```

**Comment by jjmaldonis** [comment]
It looks like the end of game stat descriptions have been removed from the response, but the descriptions are fixed now.
