### ISSUE TITLE
Datastores has no attribute ChampionGG 

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#203]
```
File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/peterli/Projects/timewindergg/Rewind/api/views.py", line 399, in get_current_match
    s = cass.get_summoner(name=summoner_name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 98, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 44, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 200, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 223, in pipeline
    verbose=0)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 30, in create_pipeline
    store_cls = getattr(module, store_name)
AttributeError: module 'cassiopeia.datastores' has no attribute 'ChampionGG'
```
```
2018-02-11 04:51:16: Internal Server Error: /get_current_match/
Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/peterli/Projects/timewindergg/Rewind/api/views.py", line 399, in get_current_match
    s = cass.get_summoner(name=summoner_name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 98, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 44, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 200, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 223, in pipeline
    verbose=0)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 30, in create_pipeline
    store_cls = getattr(module, store_name)
AttributeError: module 'cassiopeia.datastores' has no attribute 'ChampionGG'
```
```
Making call: https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/xxcode
Internal Server Error: /get_summoner/
Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/peterli/Projects/timewindergg/Rewind/api/views.py", line 225, in get_summoner
    s = cass.get_summoner(name=summoner_name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 98, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 44, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 200, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 223, in pipeline
    verbose=0)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 30, in create_pipeline
    store_cls = getattr(module, store_name)
AttributeError: module 'cassiopeia.datastores' has no attribute 'ChampionGG'
```
```
2018-02-11 04:51:16: Internal Server Error: /get_summoner/
Traceback (most recent call last):
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/peterli/Projects/timewindergg/Rewind/api/views.py", line 225, in get_summoner
    s = cass.get_summoner(name=summoner_name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/cassiopeia.py", line 98, in get_summoner
    return Summoner(id=id, account=account, name=name, region=region)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 44, in default_region_wrapper
    return method(self, *args, **kwargs)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/common.py", line 200, in __call__
    pipeline = configuration.settings.pipeline
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 223, in pipeline
    verbose=0)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/_configuration/settings.py", line 30, in create_pipeline
    store_cls = getattr(module, store_name)
AttributeError: module 'cassiopeia.datastores' has no attribute 'ChampionGG'
```

**Comment by jjmaldonis** [comment]
This has to be a problem with your environment/setup. Make sure to read the documentation/google carefully, you'll have to figure it out yourself.
