### ISSUE TITLE
Error when testing example

### ISSUE THREAD

**Issue by Jibzzz** [meraki-analytics/cassiopeia#214]
Hello,

Sorry if this question is stupid but when i'm running https://raw.githubusercontent.com/meraki-analytics/cassiopeia/master/examples/match.py I got this error :

```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/merakicommons/ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/core/staticdata/realm.py", line 57, in version
    return self._data[RealmData].version
AttributeError: 'RealmData' object has no attribute 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/merakicommons/ghost.py", line 87, in __get__
    return self.fget(obj)
  File "/usr/local/lib/python3.5/dist-packages/merakicommons/ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'RealmData' object has no attribute 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/datapipelines/sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "/usr/local/lib/python3.5/dist-packages/datapipelines/queries.py", line 323, in wrapped
    return method(self, query, context)
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/datastores/ddragon.py", line 215, in get_realms
    body = json.loads(self._client.get(url)[0])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.1.py", line 67, in <module>
    print_newest_match(name="Kalturi", account=34718348, id=21359666, region="NA")
  File "./main.1.py", line 27, in print_newest_match
    champion_id_to_name_mapping = {champion.id: champion.name for champion in cass.get_champions(region=region)}
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/cassiopeia.py", line 106, in get_champions
    return Champions(region=region)
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/core/common.py", line 213, in __call__
    query["version"] = get_latest_version(region=query["region"], endpoint=None)
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/core/common.py", line 64, in get_latest_version
    return Realms(region=region).version
  File "/usr/local/lib/python3.5/dist-packages/merakicommons/ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "/usr/local/lib/python3.5/dist-packages/cassiopeia/core/common.py", line 277, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "/usr/local/lib/python3.5/dist-packages/datapipelines/pipelines.py", line 459, in get
    return handler.get(query, context)
  File "/usr/local/lib/python3.5/dist-packages/datapipelines/pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "/usr/local/lib/python3.5/dist-packages/datapipelines/sources.py", line 71, in wrapper
    raise DataSource.unsupported(type)
datapipelines.common.UnsupportedError: The type "RealmDto" is not supported by this DataSource! ```



Does it mean i'm blacklisted or something ?

Thank you in advance.

**Comment by jjmaldonis** [comment]
Hey, I'm almost certain that the issue is that you have python 3.5 instead of 3.6. I haven't tested this specifically in a long time, but I'm 90% that we require python 3.6. Can you upgrade and try again?

**Comment by Jibzzz** [comment]
Sure, i will try it asap.
