### ISSUE TITLE
Lane KeyError: 'None'

### ISSUE THREAD

**Issue by tyuo9980** [meraki-analytics/cassiopeia#218]
Lanes can have NONE as a value, and is throwing an error when accessing participant.lane
```
>>> m = cass.get_match(2729380379, region='NA')
>>> m.participants[0].lane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/match.py", line 1080, in lane
    return self.timeline.lane
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/core/match.py", line 654, in lane
    return Lane.from_match_naming_scheme(self._data[ParticipantTimelineData].lane)
  File "/Users/peterli/miniconda3/envs/timewinder/lib/python3.6/site-packages/cassiopeia/data.py", line 311, in from_match_naming_scheme
    }[string]
KeyError: 'NONE'
```

**Comment by MingweiSamuel** [comment]
https://github.com/meraki-analytics/cassiopeia/blob/6837165c757a756d20d052155a8608a31228df8d/cassiopeia/data.py#L305-L311
