### ISSUE TITLE
Entity '<class 'cassiopeia_sqlstore.league.SQLLeague'>' has no property 'queue'

### ISSUE THREAD

**Issue by m3adow** [meraki-analytics/cassiopeia#227]
*I'm not certain if this should be here or in the datastores repo.*

When using the SQLStore plugin, there seems to be an error with saving API data of leagues.
Simple code like this:

```python
max_entries = 5
cass.ChallengerLeague(queue='RANKED_SOLO_5x5', region='EUW').entries

for i in range(max_entries):
  print(entries[i])
```
leads to an error:

```
Traceback (most recent call last):
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'ChallengerLeague' object has no attribute '_lazy__entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\cache.py", line 17, in wrapper
    value = method(self)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\cassiopeia\core\league.py", line 390, in entries
    return SearchableList([LeagueEntry.from_data(entry) for entry in self._data[ChallengerLeagueListData].entries])
AttributeError: 'ChallengerLeagueListData' object has no attribute 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\ghost.py", line 87, in __get__
    return self.fget(obj)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'ChallengerLeagueListData' object has no attribute 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\sqlalchemy\orm\base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'SQLLeague' has no attribute 'queue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/m3adow/Dropbox/Projekte/casstests/casstests/zero_usage_tester.py", line 63, in <module>
    main()
  File "C:/m3adow/Dropbox/Projekte/casstests/casstests/zero_usage_tester.py", line 40, in main
    entries = cass.ChallengerLeague(queue='RANKED_SOLO_5x5', region='EUW').entries
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\merakicommons\ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\cassiopeia\core\common.py", line 277, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\datapipelines\pipelines.py", line 459, in get
    return handler.get(query, context)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\datapipelines\pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\datapipelines\sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\datapipelines\queries.py", line 323, in wrapped
    return method(self, query, context)
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\cassiopeia_sqlstore\SQLStore.py", line 436, in get_challenger_league
    .filter_by(queue=queue) \
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\sqlalchemy\orm\query.py", line 1596, in filter_by
    for key, value in kwargs.items()]
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\sqlalchemy\orm\query.py", line 1596, in <listcomp>
    for key, value in kwargs.items()]
  File "C:\m3adow\apps\python-venvs\casstests\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'cassiopeia_sqlstore.league.SQLLeague'>' has no property 'queue'
```
These are my settings:

```
{'global': {'default_region': None,
            'enable_ghost_loading': True,
            'version_from_match': 'patch'},
 'logging': {'core': 'INFO',
             'default': 'INFO',
             'print_calls': False,
             'print_riot_api_key': False},
 'pipeline': OrderedDict([('Cache', {}),
                          ('SQLStore',
                           {'connection_string': 'postgresql+psycopg2://user:password@stampy.db.elephantsql.com/database',
                            'expirations': {'CurrentGameInfoDto': datetime.timedelta(0, 900),
                                            'LeagueListDto': datetime.timedelta(0, 7200),
                                            'MatchDto': datetime.timedelta(1),
                                            'TimelineDto': datetime.timedelta(1)},
                            'package': 'cassiopeia_sqlstore'}),
                          ('DDragon', {}),
                          ('RiotAPI', {'api_key': 'RIOT_API_KEY'})]),
 'plugins': {}}
```

**Comment by Satrium** [comment]
This is not a error in the sqlstore. The entries variable inside your loop isn't defined because you are not storing the entries you get. The flowing code does work.
```python
max_entries = 5
entries = cass.ChallengerLeague(queue='RANKED_SOLO_5x5', region='EUW').entries

for i in range(max_entries):
  print(entries[i])
```

**Comment by Satrium** [comment]
On second look, i've found this bug has been fixed in the latest PR to the sqlstore meraki-analytics/cassiopeia-datastores#5.
This PR has since been merged but isn't part of the latest release. If you want to install directly from source the following command should work:
`pip install -e 'git+https://github.com/meraki-analytics/cassiopeia-datastores#egg=cassiopeia-sqlstore&subdirectory=cassiopeia-sqlstore'`

**Comment by m3adow** [comment]
Sorry for the incomplete paste of five lines. My bad.

But yes, installing directly from the repo seems to have fixed the issue. Thanks a lot.

**Comment by jjmaldonis** [comment]
@Satrium thanks for being on top of this! Have you used the SQL store stuff quite a bit recently? If you think it's worth making another release with the code as it is right now we'll do that.

**Comment by Satrium** [comment]
I have found a few more bugs and I'm currently testing it a bit more. Will open a PR with the bugfixes soon. After that we could do another release. Will hit you up once I think it's worth to do another release.
