### ISSUE TITLE
Attribute Error: 'Match' object has no attribute '_lazy__duration'

### ISSUE THREAD

**Issue by tear727** [meraki-analytics/cassiopeia#282]
Getting this error on some matches:
`Attribute Error: 'Match' object has no attribute '_lazy__duration'`.

Full traceback:

```
Traceback (most recent call last):
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Match' object has no attribute '_lazy__duration'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/cassiopeia/core/match.py", line 1438, in duration
    return self._data[MatchData].duration
AttributeError: 'MatchData' object has no attribute 'duration'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/ghost.py", line 87, in __get__
    return self.fget(obj)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'MatchData' object has no attribute 'duration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cass_testing.py", line 359, in <module>
    test()
  File "cass_testing.py", line 279, in test
    print(match.duration)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/merakicommons/ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/cassiopeia/core/common.py", line 281, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "/Users/trentresh/anaconda/envs/cass_test/lib/python3.6/site-packages/datapipelines/pipelines.py", line 463, in get
    raise NotFoundError("No source returned a query result!")
datapipelines.common.NotFoundError: No source returned a query result!
```

**Comment by tear727** [comment]
So using the Riot API directly, the match I was querying (match 3027270879) doesn't even exist on their end. I just get a 404. Is there a proper way to except a 404 with Cass?

**Comment by robrua** [comment]
Because of the lazy loading cass does, we can't just throw a 404 when you first create the `Match`, as it hasn't tried to hit the Riot API until you request some data that wasn't provided on `Match` creation. Going forward we're trying to clean up exception handling with the lazy loading to give more useful error types to except and messages to understand.

In the meantime, I've just added `match.exists` in de3db56 which will allow you to check for this using `if match.exists:`.
