### ISSUE TITLE
Summoner Object attribute .ranks and .league_entries return an error.

### ISSUE THREAD

**Issue by impaex** [meraki-analytics/cassiopeia#294]
Here's how I've created the .ranks error:
```py
test = cass.Summoner(puuid="URB_NX8kp8quzlgxj4_Y7wDgKShdgt7hQiojeDLFzzX1pi_Gi5T4TISqQSrHcQfYeRZ3HahzAJRmDA")
print(test.ranks)
```
The error it returns is described in [issue 291](https://github.com/meraki-analytics/cassiopeia/issues/291).

Here's how I created the .league_entries error:
```py
test = cass.Summoner(puuid="URB_NX8kp8quzlgxj4_Y7wDgKShdgt7hQiojeDLFzzX1pi_Gi5T4TISqQSrHcQfYeRZ3HahzAJRmDA")
print(test.league_entries)
```
This will result in the following error:
```py
Ignoring exception in command lol sum:
Traceback (most recent call last):
  File "\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Impaex bot\cogs\LoL.py", line 68, in sum
    print(test.league_entries)
  File "\lib\site-packages\cassiopeia\core\summoner.py", line 199, in league_entries
    leagues = LeagueSummonerEntries(summoner=self)
  File "\lib\site-packages\cassiopeia\core\common.py", line 211, in __call__
    query = cls.__get_query_from_kwargs__(**kwargs)
  File "\lib\site-packages\cassiopeia\core\common.py", line 49, in default_region_wrapper
    return method(*args, **kwargs)
TypeError: __get_query_from_kwargs__() got an unexpected keyword argument 'region'
```

**Comment by jjmaldonis** [comment]
Okay, if you install Cass from github then the `.league_entries` error is fixed: `pip install -U git+https://github.com/meraki-analytics/cassiopeia.git`

The `.ranks` error should be fixed soon. We'll make a new release after that PR gets merged.
