### ISSUE TITLE
throw KeyError 401 at leagues and match examples.

### ISSUE THREAD

**Issue by queez0405** [meraki-analytics/cassiopeia#310]
`Name: Kalturi
Making call: https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-name/Kalturi
Traceback (most recent call last):
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/merakicommons/ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/core/summoner.py", line 149, in id
    return self._data[SummonerData].id
AttributeError: 'SummonerData' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/merakicommons/ghost.py", line 87, in __get__
    return self.fget(obj)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/merakicommons/ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'SummonerData' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/common.py", line 270, in __call__
    connection=self.connection)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/common.py", line 199, in get
    raise HTTPError(r.reason, r.status_code, response_headers)
cassiopeia.datastores.common.HTTPError: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassTest.py", line 38, in <module>
    print_leagues("Kalturi", "NA")
  File "cassTest.py", line 9, in print_leagues
    print("ID:", summoner.id)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/merakicommons/ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/core/common.py", line 281, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/datapipelines/pipelines.py", line 459, in get
    return handler.get(query, context)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/datapipelines/pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/datapipelines/sources.py", line 120, in get
    return source.get(type, deepcopy(query), context)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/datapipelines/sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/datapipelines/queries.py", line 326, in wrapped
    return method(self, query, context)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/summoner.py", line 48, in get_summoner
    data = self._get(url, {}, app_limiter=app_limiter, method_limiter=method_limiter)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/common.py", line 225, in _get
    return request()
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/common.py", line 276, in __call__
    return self._retry_request_by_handling_error(error)
  File "/home/esoc/DHKim/side_project/side_venv/lib/python3.6/site-packages/cassiopeia/datastores/riotapi/common.py", line 298, in _retry_request_by_handling_error
    new_handler = self.service._handlers[error.code]()
KeyError: 401`

Now I'm using python 3.6.8 and cassiopeia 4.0.8 with virtualenv environment. Somebody can help me?

**Comment by jjmaldonis** [comment]
You most likely need to set your API key in the environment variable `RIOT_API_KEY` or set it in code using `cass.set_riot_api_key("key")`.

**Comment by queez0405** [comment]
@jjmaldonis Sry. my fault. I insert wrong character in my api key lol.
