### ISSUE TITLE
ValueError: Unknown patch name 10.18

### ISSUE THREAD

**Issue by HowardHowonYu** [meraki-analytics/cassiopeia#340]
```python
Traceback (most recent call last):
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Participant' object has no attribute '_lazy__champion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cass_to_mongo_0831.py", line 254, in collect_matches
    position_ls, item_ls = get_position_start_item(new_match)
  File "cass_to_mongo_0831.py", line 111, in get_position_start_item
    cs_dict['champ'] = pt.champion.name
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 29, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1398, in champion
    version = _choose_staticdata_version(self.__match)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 61, in _choose_staticdata_version
    majorminor = match.patch.major + "." + match.patch.minor
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1668, in patch
    patch = Patch.from_str(version, region=self.region)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/patch.py", line 57, in from_str
    raise ValueError("Unknown patch name {}".format(string))
ValueError: Unknown patch name 10.18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Participant' object has no attribute '_lazy__champion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cass_to_mongo_0831.py", line 282, in <module>
    collect_matches(collection, name=sys.argv[1])
  File "cass_to_mongo_0831.py", line 256, in collect_matches
    short_match = get_position_start_item(new_match)
  File "cass_to_mongo_0831.py", line 111, in get_position_start_item
    cs_dict['champ'] = pt.champion.name
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 29, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1398, in champion
    version = _choose_staticdata_version(self.__match)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 61, in _choose_staticdata_version
    majorminor = match.patch.major + "." + match.patch.minor
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1668, in patch
    patch = Patch.from_str(version, region=self.region)
  File "/Users/yoohowon/opt/anaconda3/envs/ryencatchers/lib/python3.7/site-packages/cassiopeia/core/patch.py", line 57, in from_str
    raise ValueError("Unknown patch name {}".format(string))
ValueError: Unknown patch name 10.18
```
how can I fix this??

**Comment by jjmaldonis** [comment]
We need Riot to release the patch data for 10.18. It simply doesn't exist yet. There isn't much we can do about the static data not existing but the match object returning references to it.

You may be able to set the `version_from_match` setting to `latest` to fix this. See the "Globals" section here for info about how to add that to your settings: https://cassiopeia.readthedocs.io/en/latest/settings.html

**Comment by HowardHowonYu** [comment]
Thank you very much. Have a nice day!
