### ISSUE TITLE
match.load() causes exceptions

### ISSUE THREAD

**Issue by h4ctor** [meraki-analytics/cassiopeia#352]
I'll preface this by saying that this is my first contribution to github so if I'm doing anything wrong let me know.

Currently I'm using cassiopeia with the cassiopeia-simplekv library to fetch metch data and analyze this data. I was writing code the other day and it didn't work, so I put match.load() in there and that fixed it. Today I wrote another script where I put match.load() just in case it would run into the same issue, however match.load() actually breakes the code below and causes and exception. I think this is counterintuitive so let me share the code that doesn't work: 
```
...
for match in match_history:
        match.load()
        ...
	for participant in match.participants[Summoner].enemy_team.participants:    # oppo pinks bought
		if participant.lane == match.participants[Summoner].lane:
			opponent_vision_wards_bought_in_game.append(participant.stats.vision_wards_bought_in_game)
			opponent_wards_placed.append(participant.stats.wards_placed)
			opponent_wards_killed.append(participant.stats.wards_killed)
....
```
It throws this exception:
```
Making call: https://ddragon.leagueoflegends.com/realms/euw.json
Making call: https://euw1.api.riotgames.com/lol/match/v4/matchlists/by-account/xxxxxxxxxxxxxx6eeo-3VFOh-Mdsbi-4T4xQv4XmdXWnl89bA?beginIndex=0&endIndex=20&champion=19&queue=400&queue=420&queue=700&queue=440&api_key=xxxxxxxxxxxx

n =  20
Making call: https://ddragon.leagueoflegends.com/api/versions.json
Making call: https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-account/xxxxxxxxxxxxxxxxxxxxxFOh-Mdsbi-4T4xQv4XmdXWnl89bA?api_key=xxxxxxx
4966465213
4965937504
4964736313
4964608735
4949631710
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 602, in __getitem__
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 95, in __getitem__
    return list.__getitem__(self, item)
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\cassiopeia\core\staticdata\item.py", line 434, in name
    return self._data[ItemData].name
AttributeError: 'ItemData' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\ghost.py", line 87, in __get__
    return self.fget(obj)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'ItemData' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/admin/PycharmProjects/riotapi/data/correlation2.py", line 66, in <module>
    for participant in match.participants[Summoner].enemy_team.participants:    # oppo pinks bought
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 605, in __getitem__
    return SearchableList.__getitem__(self, item)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 97, in __getitem__
    return self.find(item)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 127, in find
    for _, x in self.enumerate(item, reverse=reverse):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 147, in enumerate
    if item in x:
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 47, in search
    if item in value:
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 47, in search
    if item in value:
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 100, in __contains__
    return self.contains(item)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 132, in contains
    for _, _ in self.enumerate(item):
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 147, in enumerate
    if item in x:
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\container.py", line 32, in search
    value = getattr(value, sub_attribute)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\merakicommons\ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\cassiopeia\core\common.py", line 281, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "C:\Users\admin\.conda\envs\riotapi\lib\site-packages\datapipelines\pipelines.py", line 463, in get
    raise NotFoundError("No source returned a query result!")
datapipelines.common.NotFoundError: No source returned a query result!

Process finished with exit code 1
```
The behaviour does not change if i delete the cached matches.
I hope this is helpful?

**Comment by jjmaldonis** [comment]
I'm sure `match.load()` isn't the problem here. It looks like it could have something to do with the items.

Can you post a complete, reproducible code example including the match ID that produces this error?

P.S. The code `match.participants[Summoner]` should have `summoner` with a lowercase `s` or it will fail. Passing in a type will not work, you need to pass in the summoner whose participant you want to get. That said, I don't believe the code is getting to this line so it should not be relevant for this error message.

**Comment by h4ctor** [comment]
This is the code:
```from datetime import *
import cassiopeia as cass
import cassiopeia_diskstore
import numpy as np
import matplotlib
import imaplib

cass.apply_settings("settings.json")
# params
n_games = 20
queues = [cass.Queue.ranked_solo_fives, cass.Queue.ranked_flex_fives, cass.Queue.clash, cass.Queue.normal_draft_fives]
champions = [cass.Champions()["Warwick"]]
Summoner = "Schuemi"
# eason = [cass.Season.season_10]
# vars
time_ccing_others = []
vision_wards_bought_in_game = []
wards_killed = []
wards_placed = []

opponent_vision_wards_bought_in_game = []
opponent_wards_killed = []
opponent_wards_placed = []

vision_wards_bought_in_game_diff = []
wards_killed_diff = []
wards_placed_diff = []

win = []


#
def mh():
	try:
		match_history =cass.get_summoner(name="SCHUEMI", region="EUW").match_history(queues=queues, end_index=n_games, champions=champions)
		return match_history

	except FileNotFoundError as ValueError:
		return []


mh = mh()
print("\nn = ", len(mh))
for match in mh:
	match.load()
	try:
		time_ccing_others.append(match.participants[Summoner].stats.time_CCing_others)
	except:
		time_ccing_others.append(0)

	try:
		vision_wards_bought_in_game.append(match.participants[Summoner].stats.vision_wards_bought_in_game)
	except:
		vision_wards_bought_in_game.append(0)

	try:
		wards_placed.append(match.participants[Summoner].stats.wards_placed)
	except:
		wards_placed.append(0)

	try:
		wards_killed.append(match.participants[Summoner].stats.wards_killed)
	except:
		wards_killed.append(0)

	for participant in match.participants[Summoner].enemy_team.participants:    # oppo pinks bought
		if participant.lane == match.participants[Summoner].lane:
			opponent_vision_wards_bought_in_game.append(participant.stats.vision_wards_bought_in_game)
			opponent_wards_placed.append(participant.stats.wards_placed)
			opponent_wards_killed.append(participant.stats.wards_killed)


	win.append(int(match.participants[Summoner].stats.win))
	print(match.id)

vision_wards_bought_in_game_diff = np.subtract(vision_wards_bought_in_game, opponent_vision_wards_bought_in_game)
wards_killed_diff = np.subtract(wards_killed, opponent_wards_killed)
wards_placed_diff = np.subtract(wards_placed, opponent_wards_placed)

r = np.corrcoef(win, vision_wards_bought_in_game_diff)[0, 1]
q = np.corrcoef(win, wards_killed_diff)[0, 1]
s = np.corrcoef(win, wards_placed_diff)[0, 1]
t = np.corrcoef(win, time_ccing_others)[0, 1]

print("\nvision_wards_bought_in_game_diff: ", r)
print("\nwards_killed_diff", q)
print("\nwards_placed_diff", s)
print("\ntime_ccing_others", t)
```
The match ID is 4941332992.
Upon removing match.load() the code runs fine except for the numpy subtraction at the end but thats my code being faulty.
