### ISSUE TITLE
Unknown patch name 11.17

### ISSUE THREAD

**Issue by rakshithxaloori** [meraki-analytics/cassiopeia#374]
`>>> participant.stats.items[0]`

```
Traceback (most recent call last):
  File "/Users/api/venv/lib/python3.9/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'ParticipantStats' object has no attribute '_lazy__items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/api/venv/lib/python3.9/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/Users/api/venv/lib/python3.9/site-packages/cassiopeia/core/match.py", line 29, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/api/venv/lib/python3.9/site-packages/cassiopeia/core/match.py", line 1066, in items
    version = _choose_staticdata_version(self.__match)
  File "/Users/api/venv/lib/python3.9/site-packages/cassiopeia/core/match.py", line 61, in _choose_staticdata_version
    majorminor = match.patch.major + "." + match.patch.minor
  File "/Users/api/venv/lib/python3.9/site-packages/cassiopeia/core/match.py", line 1678, in patch
    patch = Patch.from_str(version, region=self.region)
  File "/Users/api/venv/lib/python3.9/site-packages/cassiopeia/core/patch.py", line 57, in from_str
    raise ValueError("Unknown patch name {}".format(string))
ValueError: Unknown patch name 11.17
```

I couldn't find an 11.17 patch even in [riot versions.json](https://ddragon.leagueoflegends.com/api/versions.json)
So Riot is yet to update those files by adding the new patch.

But can you guys handle the error so as to not raise errors when there's a new patch?

**Comment by RicardoVilaca** [comment]
Same here.. Patch 11.17 needs to be included in the meraki analytics api (https://cdn.merakianalytics.com/riot/lol/resources/patches.json).

I'm not sure if a temporary solution like this would work, but let me know:
`
    @classmethod
    def __load__(cls):
        data = configuration.settings.pipeline.get(PatchListDto, query={})
        data['patches'].append({
            'name': '11.17',
            'start': 1630483200,
            'season': 11,
        })
        patches = data["patches"]
`

on cassiopeia\core\patch.py  line 82

**Comment by jjmaldonis** [comment]
This issue fixed itself over time, and I'm going to cross my fingers and hope it stays fixed given that there are no other issues raised related to this.
