### ISSUE TITLE
No source can provide "RealmData"

### ISSUE THREAD

**Issue by rasmusdoh** [meraki-analytics/cassiopeia#379]
I keep getting issues regarding "RealmData". I've tried running the match.py and summoner.py examples and same issue.
My app worked before the recent matchV5 updates to cassiopeia.

This is the error I get running the match.py example:

Making call: https://eun1.api.riotgames.com/lol/summoner/v4/summoners/by-name/VOLCAN0%20MAN
Traceback (most recent call last):
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\merakicommons\ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\cassiopeia\core\staticdata\realm.py", line 56, in version
    return self._data[RealmData].version
AttributeError: 'RealmData' object has no attribute 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\merakicommons\ghost.py", line 87, in __get__
    return self.fget(obj)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\merakicommons\ghost.py", line 43, in wrapper
    raise GhostLoadingRequiredError(str(error))
merakicommons.ghost.GhostLoadingRequiredError: 'RealmData' object has no attribute 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Rasmus/Dropbox/LoL/API tool/PythonEdition/cass test.py", line 53, in <module>
    champion_id_to_name_mapping = {champion.id: champion.name for champion in cass.get_champions(region=region)}
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\cassiopeia\cassiopeia.py", line 98, in get_champions
    return Champions(region=region)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\cassiopeia\core\common.py", line 179, in __call__
    query["version"] = get_latest_version(region=query["region"], endpoint=None)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\cassiopeia\core\common.py", line 32, in get_latest_version
    return Realms(region=region).version
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\merakicommons\ghost.py", line 90, in __get__
    obj.__load__(load_group)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\cassiopeia\core\common.py", line 250, in __load__
    data = configuration.settings.pipeline.get(type=self._load_types[load_group], query=query)
  File "C:\Users\Rasmus\anaconda3\lib\site-packages\datapipelines\pipelines.py", line 451, in get
    raise NoConversionError("No source can provide \"{type}\"".format(type=type.__name__))
datapipelines.pipelines.NoConversionError: No source can provide "RealmData"

Process finished with exit code 1

**Comment by jjmaldonis** [comment]
This should be fixed now. Closing.
