### ISSUE TITLE
ValueError: 'MATCHED_GAME' is not a valid MatchType

### ISSUE THREAD

**Issue by mgrandi** [meraki-analytics/cassiopeia#386]
version `cassiopeia         5.0.1`
```plaintext
>>> cass.set_riot_api_key("XYZ")
>>> m = cass.get_match("NA1_4057291273", cass.Region.north_america)
>>> m.load()
Making call: https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4057291273
<cassiopeia.core.match.Match object at 0x000001B2F92C6A70>
>>> m.type
Traceback (most recent call last):
  File "C:\Users\mgrandi\AppData\Local\pypoetry\Cache\virtualenvs\lpl-web-scrape-WulIR5Pl-py3.10\lib\site-packages\merakicommons\cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Match' object has no attribute '_lazy__type'. Did you mean: '_load_type'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mgrandi\AppData\Local\pypoetry\Cache\virtualenvs\lpl-web-scrape-WulIR5Pl-py3.10\lib\site-packages\merakicommons\ghost.py", line 87, in __get__
    return self.fget(obj)
  File "C:\Users\mgrandi\AppData\Local\pypoetry\Cache\virtualenvs\lpl-web-scrape-WulIR5Pl-py3.10\lib\site-packages\merakicommons\ghost.py", line 41, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\mgrandi\AppData\Local\pypoetry\Cache\virtualenvs\lpl-web-scrape-WulIR5Pl-py3.10\lib\site-packages\merakicommons\cache.py", line 17, in wrapper
    value = method(self)
  File "C:\Users\mgrandi\AppData\Local\pypoetry\Cache\virtualenvs\lpl-web-scrape-WulIR5Pl-py3.10\lib\site-packages\cassiopeia\core\match.py", line 1688, in type
    return MatchType(self._data[MatchData].type)
  File "C:\Python310\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "C:\Python310\lib\enum.py", line 701, in __new__
    raise ve_exc
ValueError: 'MATCHED_GAME' is not a valid MatchType
>>>
```

json output:

[tmp_lol_match_json.txt](https://github.com/meraki-analytics/cassiopeia/files/7356374/tmp_lol_match_json.txt)

**Comment by jjmaldonis** [comment]
This must have been fixed in a previous PR.
