### ISSUE TITLE
AttributeError: 'MatchReferenceData' object has no attribute 'creation'

### ISSUE THREAD

**Issue by ribatturan** [meraki-analytics/cassiopeia#393]
Full traceback:
```
Traceback (most recent call last):
  File "C:/Users/ribat/OneDrive/Masaüstü/cassiopeia-master/examples/cassTest.py", line 61, in <module>
    print_matches(name="Robin smurfer", region="EUW")
  File "C:/Users/ribat/OneDrive/Masaüstü/cassiopeia-master/examples/cassTest.py", line 25, in print_matches
    for match in match_history:
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\merakicommons\container.py", line 355, in __iter__
    yield next(self)
  File "D:\Program Files (x86)\Python\Python38-32\lib\site-packages\merakicommons\container.py", line 368, in __next__
    value = next(self._generator)
  File "C:\Users\ribat\OneDrive\Masaüstü\cassiopeia-master\cassiopeia\datastores\ghost.py", line 454, in generate_matchlists
    _earliest_dt_in_current_match_history = matchrefdata.creation
```
I updated from "fix_wrong_parameters_match_v5" and then this problem exist. Before updating match.py i only see 20 matches(default value) because of the wrong parameters. But now i'm having this error.

**Comment by jjmaldonis** [comment]
This is fixed now, see #412
