### ISSUE TITLE
Participant' object has no attribute '_lazy__champion'

### ISSUE THREAD

**Issue by kindalime** [meraki-analytics/cassiopeia#399]
Hello! I am running the `match.py` example in the `examples` folder. However, when I do, I run into the error `Participant' object has no attribute '_lazy__champion'`.

Full error log:
```
Traceback (most recent call last):
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/merakicommons/cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Participant' object has no attribute '_lazy__champion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 69, in <module>
    print_newest_match(name="Perkz", region="NA")
  File "test.py", line 28, in print_newest_match
    champion_id = match.participants[summoner].champion.id
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/merakicommons/cache.py", line 17, in wrapper
    value = method(self)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/match.py", line 30, in wrapper
    return method(self, *args, **kwargs)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1497, in champion
    version = _choose_staticdata_version(self.__match)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/match.py", line 62, in _choose_staticdata_version
    majorminor = match.patch.major + "." + match.patch.minor
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/match.py", line 1734, in patch
    patch = Patch.from_str(version, region=self.region)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/patch.py", line 48, in from_str
    cls.__load__()
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/core/patch.py", line 80, in __load__
    data = configuration.settings.pipeline.get(PatchListDto, query={})
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/datapipelines/pipelines.py", line 459, in get
    return handler.get(query, context)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/datapipelines/pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/datapipelines/sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "/home/daniel/venv/discord/lib/python3.7/site-packages/cassiopeia/datastores/merakianalyticscdn.py", line 47, in get_patch_list
    body = json.decode(body)
  File "/usr/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Thank you very much!

**Comment by jjmaldonis** [comment]
This seems to be working now. Feel free to reopen it with a comment if you are still seeing this bug.
