### ISSUE TITLE
AttributeError: 'Match' object has no attribute '_lazy__timeline'

### ISSUE THREAD

**Issue by feytus** [meraki-analytics/cassiopeia#422]
Hello, I get an error when I try to get data from a match at a specific time in it, but when I run the function I get an error.

# **The code**
```python
def get_build(name: str, region: str):
    summoner = Summoner(name=name, region=region)
    
    match = summoner.match_history[0]
    
    p: Participant = match.participants[summoner]

    p_state = p.cumulative_timeline[match.duration]

    items = p_state.items
    items = [item.name for item in items]
    runes = [runes.name for runes in p.runes]
    
    dict = {"Champion": p.champion.name, "Individual Position": p.individual_position.name, "Items": items, "Runes": runes}
    return dict

name = "Feytus"
region = "EUW"

print(get_build(name=name, region=region))
```

# **The output**
```
Making call: https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/Feytus
{'continent': <Continent.europe: 'EUROPE'>, 'puuid': 'vWuB1tTJHOsCHfR4MRu8VWiFoBDz-ncRQcUd0oixgtV_mDx63klyjAwYBhvFf8oLGXqF2SmhnQmE5A'}
Making call: https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/vWuB1tTJHOsCHfR4MRu8VWiFoBDz-ncRQcUd0oixgtV_mDx63klyjAwYBhvFf8oLGXqF2SmhnQmE5A/ids?start=0&count=100
Making call: https://europe.api.riotgames.com/lol/match/v5/matches/EUW1_6001718177
Traceback (most recent call last):
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\merakicommons\cache.py", line 15, in wrapper
    return getattr(self, s)
AttributeError: 'Match' object has no attribute '_lazy__timeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\repos\feytus\OTPBuilds\main.py", line 74, in <module>
    print(get_build(name=name, region=region), end="\n")
  File "c:\repos\feytus\OTPBuilds\main.py", line 62, in get_build
    p_state = p.cumulative_timeline[match.duration]
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\cassiopeia\core\match.py", line 915, in __getitem__      
    state = ParticipantState(
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\cassiopeia\core\match.py", line 939, in __init__
    for frame in participant_timeline.frames:
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\cassiopeia\core\match.py", line 846, in frames
    for frame in self.__match.timeline.frames:
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\merakicommons\cache.py", line 17, in wrapper
    value = method(self)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\cassiopeia\core\match.py", line 1980, in timeline        
    self._timeline = Timeline(id=self.id, continent=self.continent)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\cassiopeia\core\common.py", line 198, in __call__        
    return pipeline.get(cls, query=query)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\pipelines.py", line 459, in get
    return handler.get(query, context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\pipelines.py", line 185, in get
    result = self._source.get(self._source_type, deepcopy(query), context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\sources.py", line 69, in wrapper
    return call(self, query, context=context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\queries.py", line 325, in wrapped
    validator(query)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\queries.py", line 209, in __call__
    return self._root.evaluate(query, context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\queries.py", line 60, in evaluate
    child.evaluate(query, context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\queries.py", line 198, in evaluate
    self.child.evaluate(query, context)
  File "C:\repos\feytus\OTPBuilds\.venv\lib\site-packages\datapipelines\queries.py", line 173, in evaluate
    raise WrongValueTypeError("{key} must be of type {type} in query! Got {badtype}.".format(key=self.key, type=self, badtype=type(value)))
datapipelines.queries.WrongValueTypeError: id must be of type str in query! Got 6001718177.
```

**Comment by jjmaldonis** [comment]
@feytus I wasn't able to reproduce the exact error but I used your code and fixed the errors that I ran into. If you pull the latest version from github, this should be fixed. Feel free to reopen it with a comment if you are still running into issues after updating from github - I may make a pypi release later if I get a handful of other things fixed.
