### ISSUE TITLE
[BUG] baseriotapi.get_shard()

### ISSUE THREAD

**Issue by TiFu** [meraki-analytics/cassiopeia#70]
Hey,

I think I found a bug. 

If you execute this python code (I tested it with python 3 & 3.5):

```python
from cassiopeia import baseriotapi

baseriotapi.set_region("na")
baseriotapi.set_api_key("API_KEY")

content = baseriotapi.get_shard()
```

This traceback appears:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    content = baseriotapi.get_shard()
  File "/tmp/cassiopeia/dto/statusapi.py", line 24, in get_shard
    return cassiopeia.type.dto.status.ShardStatus(cassiopeia.dto.requests.get(request, static=True, include_base=False))
  File "/tmp/cassiopeia/dto/requests.py", line 41, in get
    return make_request(request=request, method="GET", params=params, static=static, include_base=include_base, tournament=tournament)
  File "/tmp/cassiopeia/dto/requests.py", line 91, in make_request
    content = limiter.call(execute_request, url, method, payload) if limiter else execute_request(url, method, payload)
  File "/tmp/cassiopeia/type/api/rates.py", line 158, in call
    return method(*args) if method else None
  File "/tmp/cassiopeia/dto/requests.py", line 134, in execute_request
    content = zlib.decompress(content, zlib.MAX_WBITS | 16).decode(encoding="UTF-8")
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by jjmaldonis** [comment]
Thanks for the report.

@robrua You have any ideas on this one? Otherwise I will dig into it when I get a chance.

**Comment by robrua** [comment]
I'll take a look tonight - seems like that endpoint may just not support gzip.

**Comment by robrua** [comment]
Yeah. We (read "I") were assuming all endpoints will do gzip encoding if we request it. Added a check for whether it got an encoded response in #870c2a3b563acadcdfde0547aff28e8208b55cda

This should solve your problem if you pull the latest
