### ISSUE TITLE
Some 404 Error?

### ISSUE THREAD

**Issue by alyssa-adams** [meraki-analytics/cassiopeia#92]
Hello all!

Another super nubly question ahead...
I've been trying to pull data from the server for the last couple of days and I'm constantly running into this error. Is there anything I can do to avoid this problem?

Thank you in advance!

```
Got Match #2382824374
Got Match #2382829987
Got Match #2382765735
Got Match #2382770977
Got Match #2382712711
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 92, in make_request
    content = limiter.call(execute_request, url, method, payload) if limiter else execute_request(url, method, payload)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/api/rates.py", line 158, in call
    return method(*args) if method else None
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 134, in execute_request
    response = urllib.request.urlopen(request)
  File "//anaconda/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "//anaconda/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "//anaconda/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "//anaconda/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "//anaconda/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "//anaconda/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pull_masters_tier_loop.py", line 147, in <module>
    main()
  File "pull_masters_tier_loop.py", line 63, in main
    for match in summoner.match_list(begin_time=gather_start):
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/core/common.py", line 108, in curried
    return self.method(obj, *args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/type/core/summoner.py", line 265, in match_list
    return cassiopeia.riotapi.get_match_list(self, num_matches, begin_index, begin_time, end_time, champions, ranked_queues, seasons)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/core/matchlistapi.py", line 52, in get_match_list
    history = cassiopeia.dto.matchlistapi.get_match_list(summoner.id, num_matches, begin_index, begin_time, end_time, champion_ids, ranked_queues, seasons)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/matchlistapi.py", line 40, in get_match_list
    return cassiopeia.type.dto.matchlist.MatchList(cassiopeia.dto.requests.get(request, params))
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 42, in get
    return make_request(request=request, method="GET", params=params, static=static, include_base=include_base, tournament=tournament)
  File "//anaconda/lib/python3.5/site-packages/cassiopeia/dto/requests.py", line 107, in make_request
    raise cassiopeia.type.api.exception.APIError("Server returned error {code} on call: {url}".format(code=e.code, url=url), e.code)
cassiopeia.type.api.exception.APIError: Server returned error 404 on call: https://na.api.pvp.net/api/lol/na/v2.2/matchlist/by-summoner/83039128?api_key=xxx&beginTime=1482710400000
```

**Comment by jjmaldonis** [comment]
That's strange. The summoner endpoint works for that summoner ID, but the mathlist endpoint does not.

I only have one idea: maybe the summoner doesn't have any games played this season and Riot doesn't have them in their database anymore (which doesn't make a whole lot of sense). Otherwise I have no idea what's going on. If you are able to collect a bunch of examples of this happening, you may be able to find a pattern, but otherwise I don't know...

**Comment by alyssa-adams** [comment]
Hm, that's really odd. I'm pulling the matches from Challenger/Master tier. First, I gather the list of those 200 summoners, then I collect all their matches from some date to some date. As a work around this problem, would it be possible to get the summoner list of Challenger players as of a certain date? For example, if I wanted all Challenger matches from 24 Dec 2016, could I figure out who the Master players were on 24 Dec, then pull the matches? And just work it day by day?

**Comment by jjmaldonis** [comment]
As far as I know that's not possible, but it's probably worth asking on the forums. Maybe someone else will know.

**Comment by alyssa-adams** [comment]
Ok! Do you know which forums would be the most helpful?

**Comment by jjmaldonis** [comment]
Ah, the Riot API dev forums -- if you don't go on them much, they can be very helpful.

Link: https://developer.riotgames.com/discussion/community-discussion

**Comment by alyssa-adams** [comment]
Awesome, thank you so much!

**Comment by alyssa-adams** [comment]
Actually, as a general python question, is there any way I can have my code print a message after it returns all that error information? I would like to what summoner name it was on so I don't have to restart the data pull from the very beginning every single time. (I'm trying to pull about a month's worth of data from the challenger tier and it's not practical to keep restarting the data pull).

**Comment by jjmaldonis** [comment]
Closing old issues because many things have changed with the Cass rewrite.
